### ISSUE TITLE
Decide whether to drop datetime information

### ISSUE THREAD

**Issue by uliska** [timvink/mkdocs-git-authors-plugin#19]
As discussed in https://github.com/timvink/mkdocs-git-authors-plugin/pull/12#discussion_r387568752 retrieving the last-modification timestamp for a given page doesn't actually have a use case within the context of the plugin. Dropping support for it (also from the resulting `git_author` dictionary in the page context) would make implementation more straightforward.

However, *if* we decide to keep the Git classes proposed in #12 *and* to merge the plugin with `mkdocs-revision-date-localized` it makes sense to also determine that value from the `git blame` data.

So: if the two decisions are *not* taken  support for that value should be removed (from `Commit._populate()` or probably `Page._process_git_blame()` by then).

**Comment by timvink** [comment]
We have decided to keep the Git classes, and I updated the #16, as it makes sense to combine both git date and author functionality in the future.

There is one more consideration. For date, currently we use `git log -n 1 -p <file path>` to get the latest commit on a file. Replacing that with parsing `git blame --porcelain` for the commit with the most recent date seems like we're doing the same thing, but I'm not sure how if there are differences when shallow clones (`git clone --depth 1`) are made. (background on shallow clone problem in https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/10))

For now, I see no reason yet to drop datetime information from the codebase.
