### ISSUE TITLE
Make output configurable through template partials

### ISSUE THREAD

**Issue by timvink** [timvink/mkdocs-git-authors-plugin#21]
As discussed in https://github.com/timvink/mkdocs-git-authors-plugin/pull/12#discussion_r387023642 it might be a nice idea to provide template partials (like in MkDocs themes) to make the output configurable to users.

_Originally posted by @uliska in https://github.com/timvink/mkdocs-git-authors-plugin/issues/16#issuecomment-594442834_

**Comment by timvink** [comment]
The default output of `{{ git_authors_summary }}` is a oneline sentence with something like `Jane Doe, John Doe`.

This will not fit the needs of every users. Changes can be made via CSS (there is a `<span class='git-authors'></span>`), but the plugin also adds a variable to the jinja context with a `dict` like:

```python
[{
    'name' : 'Jane Doe',
    'email' : 'jane@abc.com',
    'last_datetime' : datetime.datetime(),
    'lines' : 200,
    'contribution' : '40.0%'
}]
```

Currently, the only way to use that information is through [overriding partials or template blocks](https://squidfunk.github.io/mkdocs-material/customization/#overriding-template-blocks). 

In https://github.com/timvink/mkdocs-git-authors-plugin/pull/12#discussion_r387046164 @uliska and discuss whether to implement a list summary version. 

I argued not to add extra markdown_tags or options, but force the user to use partials or template blocks for customisation. @uliska suggested we could implement template partials.

This issue is to discuss a possible design for this.

**Comment by timvink** [comment]
I have another idea. 

`{{ git_authors_summary }}` outputs something like:

`<span class='git-authors'><a href='mailto:jane@abc.com'>Jane Doe</a><a href='mailto:john@abc.com'>John Doe</a></span>`

which we could change to:

`<span class='git-authors'><ul><li><a href='mailto:jane@abc.com'>Jane Doe</a></li><li><a href='mailto:john@abc.com'>John Doe</a></li></ul></span>`

Then, by default, we add a CSS class `.git-authors {}` to the page, that will make sure to display this list inline by default. 

In this way, basic customization can be done via CSS. Extending this idea further, we could even already include all the line counts, but `display: none` them by default.

**Comment by uliska** [comment]
I think this goes absolutely in the right direction regarding your ideas about interface and simplicity.

There's just one thing I'd note: Typically the inline list goes in a page footer (to be rendered on *every* page) while the full list is an individual item to be rendered on a single page. That means on a page where the full list is requested there will typically be the current-page-authors in the footer as well.

I think this could be approached by having `<span class='git-authors inline'>` and `<span class='git-authors full-list'>` or any other differentiating additional class. `inline` could also be taken as the default and *not* be rendered. Basically there has to be an additional class to be used for the single item on a real page.

However, that doesn't answer the question of the user interface. A simple way would be to allow `{{ git_authors_summary full-list }}` or similar. But of course that's not much different from providing a second independent tag.

**Comment by timvink** [comment]
OK, after reading your comment I realise the CSS route is not going to be any cleaner. Thought about it more, and also realized injecting CSS is going to be hard to overwrite, or lead to unexpected behaviour. 

I'm going to change my mind 🙈Sorry for pressing this issue so much, I think you made the right call all along.

I would only propose to change the naming for clarity. So we would provide these markdown tags:

- `{{ git_authors_page }}` - The inline list with the current page's author
- `{{ git_authors_site }}` - The list with the site's authors. I choose 'site' instead of 'book' because mkdocs is a 'static site generator'. 
- `{{ git_authors_summary }}` will remain the same for backward compatibility but hidden for users.

**Comment by uliska** [comment]
Do I understand correctly that `{{ git_authors_page }}` is the *same* as the current "summary"? I'm just asking because that seems to make much sense, but "the current page's author" (note the singular) might also indicate a different intention.

**Comment by timvink** [comment]
Typo. I meant "the current page's authors" (updated in post now). 

Alternatively, we could go for:

- `{{ git_page_authors }}`
- `{{ git_site_authors }}`

Which might fit nicely with a future

- `{{ git_page_last_updated }}`
- `{{ git_site_last_updated }}`

**Comment by timvink** [comment]
@uliska I just released [v.0.3.0](https://github.com/timvink/mkdocs-git-authors-plugin/releases/tag/v0.3.0) 🎉 

I will close this issue for now: configuration is possible through:

1) multiple preconfigured markdown tag 
1) unique CSS `<span>` classes for each markdown tag. 

Feel free to re-open to discuss further ideas on templating
