### ISSUE TITLE
Decide how to provide an authors summary on repository level.

### ISSUE THREAD

**Issue by uliska** [timvink/mkdocs-git-authors-plugin#22]
As part of #12 a new tag `git_authors_list` has been added, but as discussed in https://github.com/timvink/mkdocs-git-authors-plugin/pull/12#discussion_r387527321 it is not clear how this really should be achieved in terms of user-facing simplicity and configurability.

The data is there and can be requested from an `Author` simply by not specifying a target page in `Author.lines()` or `Author.contribution()`.

For now this is going to be merged as part of the Pull Request, but the question has to be fully resolved before the next release.

**Comment by timvink** [comment]
We missed each other, I created #21. The outcome of that discussion would resolve this one.
