### ISSUE TITLE
Authors tag is showing in page content but no into the partials

### ISSUE THREAD

**Issue by Guts** [timvink/mkdocs-git-authors-plugin#34]
👏 Great work this new version! 👏 

Nevertheless, I'm noticing some minor issue: the authors summary is displayed when the tag is included into the page content, but not in _partials_.

FYI: it was working fine with the master branch that I've used on past Sunday.

To reproduce:
1. I created a fixture with the Material theme activated and [an extended view as described in the README](https://github.com/timvink/mkdocs-git-authors-plugin#in-theme-customizations): if you want, check [my fork with this test fixture](https://github.com/Guts/mkdocs-git-authors-plugin)
2. Launch on localhost: `mkdocs serve -f .\tests\basic_setup\mkdocs_complete_material.yml`

And the result:

![image](https://user-images.githubusercontent.com/1596222/78152116-aea18400-7439-11ea-9e5a-05d878d2218b.png)

**Comment by timvink** [comment]
Oh oh, that looks like a bug. Will have a look at it tomorrow, thanks for reporting!

**Comment by timvink** [comment]
Released a new version [v0.3.1.](https://github.com/timvink/mkdocs-git-authors-plugin/releases/tag/v0.3.1) that fixes this. Thanks for your contributions!
