### ISSUE TITLE
Plain text output for HTML meta tag

### ISSUE THREAD

**Issue by AlphaJack** [timvink/mkdocs-git-authors-plugin#49]
I was wondering if there was a way to get a plain text list of authors, i.e.

```
Turbato Thomas, Elodeon Nick
```

instead of

```html
<span class="git-page-authors git-authors"><a href="mailto:thomas@turba.to">Turbato Thomas</a> (98.0%), <a href="mailto:nick@elodeon.tv">Elodeon Nick</a> (2.0%)</span>
```

In this way one could set the page "author" meta tag without the need to specify authors manually in the markdown file, as MkDocs Material does here:

```html
{% if page and page.meta and page.meta.author %}
  <meta name="author" content="{{ page.meta.author }}">
{% elif config.site_author %}
  <meta name="author" content="{{ config.site_author }}">
{% endif %}
```

Setting the tag would also make the website appear like this in Firefox reader view:
![authors](https://user-images.githubusercontent.com/19962243/110029841-e0e3f180-7d2c-11eb-8026-ea0901c115a5.png)

**Comment by timvink** [comment]
> I was wondering if there was a way to get a plain text list of authors, i.e.

Yes, you could use the `{{ git_info }}` object to achieve this when overriding a template block. See the docs for an example: https://timvink.github.io/mkdocs-git-authors-plugin/usage.html#in-theme-templates

> In this way one could set the page "author" meta tag without the need to specify authors manually in the markdown file, as MkDocs Material does here:

I am not sure I understand your use case.

That said, adding an option to set `plain_text: true` shouldn't be too much work, and I'd gladly accept a PR for this.

**Comment by timvink** [comment]
Note that you can now either:

- Set the option `show_email_address` to `false` (https://timvink.github.io/mkdocs-git-authors-plugin/options.html#show_email_address)
- Use [theme customization](https://timvink.github.io/mkdocs-git-authors-plugin/usage.html#in-theme-customizations) and the `git_info` variable to customize your site
