### ISSUE TITLE
Util.get_authors() - type argument?

### ISSUE THREAD

**Issue by uliska** [timvink/mkdocs-git-authors-plugin#5]
What is the `type` argument in Ùtil.get_authors()` supposed to be doing:

https://github.com/timvink/mkdocs-git-authors-plugin/blob/130d4de4a03281f94285ff8c217b0c29cacc98d4/mkdocs_git_authors_plugin/util.py#L9-L19

The method signature's default value contradicts the docstring, and the argument is not used at all in the method.

**Comment by timvink** [comment]
Good point! This was initially there to be able to choose different methods of retrieving git authors. So not only `email` or `name`, but also `author` vs `committer` ([SO post](https://stackoverflow.com/questions/18750808/difference-between-author-and-committer-in-git)). In the end I decided to keep it simple for users and abstract it away, choosing `author`.

Will clean up now, thnx!
