### ISSUE TITLE
Add enable_if_env option

### ISSUE THREAD

**Issue by ldeluigi** [timvink/mkdocs-git-authors-plugin#51]
Like https://github.com/zhaoterryy/mkdocs-git-revision-date-plugin#enabled_if_env

It's useful in a CI environment where you don't know if there is a git repository available

**Comment by ldeluigi** [comment]
A fallback to empty author would also be fine if git is not available

**Comment by timvink** [comment]
I like the fallback option better. When git is not available we can fallback to disabling the plugin (with a warning). 

For the implementation we can borrow from https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/#fallback_to_build_date. 

Would you be willing to contribute a PR for this?

**Comment by ldeluigi** [comment]
At the moment I'm too busy. I'll look at it when I get some free time, sorry.
