### ISSUE TITLE
Wrong output with fallback_to_empty warning

### ISSUE THREAD

**Issue by ldeluigi** [timvink/mkdocs-git-authors-plugin#53]
Whith fallback_to_empty set to `true` and without a proper Git environment I get the following warning message:
![image](https://user-images.githubusercontent.com/44567586/127857067-9439c9b9-8d87-4715-8efd-8a9c4daf9c97.png)
As you can see from the first line in the screenshot the syntax is wrong. (I made the mistake but I don't know how to solve it)

See: https://github.com/timvink/mkdocs-git-authors-plugin/blob/e47d604e60bf009672d78fb7a5a83e573f9c16dc/mkdocs_git_authors_plugin/plugin.py#L53-L56

**Comment by timvink** [comment]
Good attention for detail, thanks for reporting! I also missed it in my review, fixed now in 209a886c4d7e808a603cd7b6a0573446084fa2c8 and just released in `v0.4.1`

Thanks!
