### ISSUE TITLE
Remove or hide mailto hyperlink from author

### ISSUE THREAD

**Issue by CaloC-NZ** [timvink/mkdocs-git-authors-plugin#56]
Is there any way to disable the mailto hyperlink on the author, i.e. have the author name display, but not have it as a clickable link, just have it as plain text.

Also, thanks for the exclude update, works like a charm.

**Comment by timvink** [comment]
Did you see #49 ? Seems like a duplicate. If so, can you reply there & close this issue?

**Comment by CaloC-NZ** [comment]
Legend, exactly what I needed.
