### ISSUE TITLE
{{ git_site_authors }} - Conflict with macros plugin?

### ISSUE THREAD

**Issue by Guts** [timvink/mkdocs-git-authors-plugin#60]
# Description

I've noticed a few months ago (sorry for this delayed report) that my site authors list is empty since I've enabled the excellent [Macros Plugin](https://github.com/fralau/mkdocs_macros_plugin) of @fralau.

I guess it's a Jinja conflict but I can't figure out where or why (nothing in log). Note that the `git_page_authors` is working...

## How to reproduce

1. Create a new mkdocs site
2. Add git authors plugin and site tags into index.md
3. commit everything
4. mkdocs serve --> authors list is rendered:

  ![image](https://user-images.githubusercontent.com/1596222/148429631-4fab1df9-1440-4ba8-95fa-249a9c181a89.png)

5. add macros plugin
6. mkdocs serve --> authors list is not rendered:

  ![image](https://user-images.githubusercontent.com/1596222/148429574-11b98d2e-eb41-4ec1-bb6c-c5245319c908.png)

`mkdocs.yml`:

```yaml
site_name: My Docs

plugins:
  - search
  - git-authors
  - macros
```

`docs/index.md`:

```markdown
# Welcome to MkDocs

For full documentation visit [mkdocs.org](https://www.mkdocs.org).

## Commands

* `mkdocs new [dir-name]` - Create a new project.
* `mkdocs serve` - Start the live-reloading docs server.
* `mkdocs build` - Build the documentation site.
* `mkdocs -h` - Print help message and exit.

## Project layout

    mkdocs.yml    # The configuration file.
    docs/
        index.md  # The documentation homepage.
        ...       # Other markdown pages, images and other files.

## Site authors

{{ git_site_authors }}

**Comment by timvink** [comment]
Thanks for reporting! I'm able to reproduce this. In fact, if I change the order of plugins:

```
plugins:
  - search
  - macros
  - git-authors
```

Then `{{ git_page_authors }}` also produces empty output.

Will investigate.

**Comment by timvink** [comment]
I found & solved the issue, see https://github.com/fralau/mkdocs_macros_plugin/pull/116 . I will leave this issue open until the PR is approved and a new `macros-plugin` version is released.

**Comment by Guts** [comment]
Nice!

Thanks you!

**Comment by timvink** [comment]
`mkdocs_macros_plugin` v.0.6.4 is now pushed on pypi. The unit tests I wrote for this issue [now pass](https://github.com/timvink/mkdocs-git-authors-plugin/pull/61/checks).

`pip install --upgrade mkdocs_macros_plugin` and you're good to go :)
