### ISSUE TITLE
git profile insteed of email link

### ISSUE THREAD

**Issue by fire1ce** [timvink/mkdocs-git-authors-plugin#63]
I'm not comfortable to Include unnecessary emails of contributors on mkdocs pages. It's prone to be fetch easly with bots.
Is it posable to make an option for link to the git profile of the contributor? I think it more responable way to link someone for help

**Comment by timvink** [comment]
It is, but you would need to use the GitHub API. Use the https://github.com/byrnereese/mkdocs-git-committers-plugin for that use case !
