### ISSUE TITLE
Allow to link github profiles rather than e-mails

### ISSUE THREAD

**Issue by adamant-pwn** [timvink/mkdocs-git-authors-plugin#64]
I feel like personal e-mail is not kind of info contributors would like to get exposed on widely viewed pages. I was at first hoping to customize it with [git_info](https://timvink.github.io/mkdocs-git-authors-plugin/usage.html), but github usernames are not stored. Could you please make an option to access github usernames instead of emails?

**Comment by adamant-pwn** [comment]
Sorry, I see that it's a duplicate of https://github.com/timvink/mkdocs-git-authors-plugin/issues/63.

**Comment by timvink** [comment]
Yeah. And squidfunk is working on a [tighter integration with mkdocs-material](https://twitter.com/squidfunk/status/1530569101982179328) also, which is going to look great.
