### ISSUE TITLE
ingmarkdown templates not available for R 2022.07.1 Build 554

### ISSUE THREAD

**Issue by monicaatjes** [timvink/mkdocs-git-authors-plugin#65]
Hi Tim, 
Hopefully you are doing well and feel happy with your new role. I am still using your developed package ingmarkdowntemplates, but after I reinstalled R I keep getting the message that it is not compatible anymore with this version of R. Do you know what I should do? 
Many thanks in advance!! 
All the best,
Moniek

**Comment by timvink** [comment]
I've contacted you directly.
