### ISSUE TITLE
Not tested with py311 - deprecation warnings

### ISSUE THREAD

**Issue by ssbarnea** [timvink/mkdocs-git-authors-plugin#70]
The fact that this plugin is not tested with py311 prevented it from finding some deprecation runtime warnings:
```
INFO     -  DeprecationWarning: pathlib.Path.__enter__() is deprecated and scheduled for removal in Python 3.13; Path objects as a context manager is a no-op
              File "/opt/homebrew/lib/python3.11/site-packages/mkdocs_git_authors_plugin/ci.py", line 23, in raise_ci_warnings
                with Path(path):
              File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 891, in __enter__
                warnings.warn("pathlib.Path.__enter__() is deprecated and scheduled "
INFO     -  Cleaning site directory
```

BTW, If you want to avoid having to update the list of python version on GHA, you might find https://github.com/coactions/dynamic-matrix useful.

**Comment by timvink** [comment]
Thanks for mentioning. I can't seem to reproduce the warning locally (python 3.11.0). Made a change to the context manager nonetheless, hopefully that fixes it. Can you try installing from the `master` branch?

**Comment by timvink** [comment]
3.11 has also been added to the github actions matrix, see https://github.com/timvink/mkdocs-git-authors-plugin/actions/runs/4221698161/jobs/7329305103

**Comment by ssbarnea** [comment]
Thanks. I will make a PR if I spot it again. Maybe they changes something in 3.11.1 or 3.11.2. Anyway, now that we have it tested, it will be very easy to patch it.

**Comment by SilentGlasses** [comment]
Hey yo...  I didn't want to create a new issue when this one exists..   I just installed this pluin and have this issue... Do you know if this fix got merged into the plugin already or if not, can we get it added in?

```
INFO     -  DeprecationWarning: pathlib.Path.__enter__() is deprecated and scheduled for removal in Python 3.13; Path objects as a context manager is a no-op
              File "/usr/local/lib/python3.11/site-packages/mkdocs_git_authors_plugin/ci.py", line 23, in raise_ci_warnings
                with Path(path):
              File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 891, in __enter__
                warnings.warn("pathlib.Path.__enter__() is deprecated and scheduled "
```

`pip list` shows: 

```
mkdocs-git-authors-plugin==0.7.0
```

Thanks for looking into this.

**Comment by SilentGlasses** [comment]
ALos, not sure if thi

> 3.11 has also been added to the github actions matrix, see https://github.com/timvink/mkdocs-git-authors-plugin/actions/runs/4221698161/jobs/7329305103

Not sure if this matters but during the unit tests, it seems to be using `python@v2` not v3...

**Comment by ldeluigi** [comment]
https://github.com/timvink Could you please release the fix?

**Comment by ldeluigi** [comment]
@timvink Could you please release the fix?

**Comment by ldeluigi** [comment]
@timvink Could you please release the fix?

**Comment by timvink** [comment]
Sorry for the very long delay. v0.7.1 just hit pypi. Please re-open this issue if this doesn't solve it.
