### ISSUE TITLE
Is there a way to get mkdocs-git-authors-plugin to respect Git `.mailmap` files?

### ISSUE THREAD

**Issue by JPStrydom** [timvink/mkdocs-git-authors-plugin#77]
When an author used multiple email addresses to commit to a repo, Git recommends using a [`.mailmap`](https://git-scm.com/docs/gitmailmap) file to help treat these email addresses as one user. For example:

Jon Smith commits with `jon@gmail.com`, `jon-s@company.com` and with `jon.smith@yahoo.com`. Using a tool like [`git-quick-stats`](https://git-quick-stats.sh/), we'll see a Git author summary along the lines of:
```
Jon <jon@gmail.com> (10%)
Jon Smith <jon.smith@yahoo.com> (50%)
Jon Smith <jon-s@company.com> (40%)
```

If we then add the following `.mailmap` file to the root of the repo:
```
Jon Smith <jon.smith@yahoo.com> <jon@gmail.com>
Jon Smith <jon.smith@yahoo.com> <jon-s@company.com>
```
Which essentially tells Git:
```
Preferred Name <preferred-email> <email-to-alias-to-preferred>
```

After adding this file, we'll see a Git author summary along the lines of:
```
Jon Smith <jon.smith@yahoo.com> (100%)
``` 

mkdocs-git-authors-plugin, however, does not seem to take the `.mailmap` file into account, as the `git_page_authors` variable still includes an entry for each email address's user:
```
Jon, Jon Smith, Jon Smith
```

Is there a way to get mkdocs-git-authors-plugin to take the `.mailmap` file into account, or is there another way we can tell mkdocs-git-authors-plugin to treat multiple email addresses as one user?

**Comment by timvink** [comment]
. mailmap should work, we even recommend it in the documentation: https://timvink.github.io/mkdocs-git-authors-plugin/mailmap.html

Under the hood, this plugin is using normal `git blame` commands.

Can you confirm/test that the mailmap is working on the command line, but not with the plugin?

**Comment by JPStrydom** [comment]
Thanks for the feedback! 

Here are the relevant portions of our `.mailmap` file:
```
JP S<jp.s@redacted.co.za> <DXtL4PyW7ExnRyGAbEvA>
Matthew V<matthew.v@redacted.co.uk> <matthew.v@redacted.co.za>
Matthew V<matthew.v@redacted.co.uk> <matthew.v@redacted.com>
```

With our `.mailmap` file present, an example `git blame` looks as follows:
```
JP S <jp.s@redacted.co.za>
...
JP S <jp.s@redacted.co.za>
...
Matthew V <matthew.v@redacted.co.uk>
...
Matthew V <matthew.v@redacted.co.uk>
...
Matthew V <matthew.v@redacted.co.uk>
```

Without our `.mailmap` file present, an example `git blame` looks as follows:
```
jp.s <DXtL4PyW7ExnRyGAbEvA>
...
JP S <jp.s@redacted.co.za>
...
Matthew V <matthew.v@redacted.co.uk>
...
Matthew V <matthew.v@redacted.co.za>
...
matthew.v <matthew.v@redacted.co.uk>
```

So it appears that the `.mailmap` file and `git blame` are aggregating the users correctly.

Here's how we're using the plugin (_Please do advise if there is a more-correct way to use it_):
```
{% extends "base.html" %}

{% block content %}
  {{ super() }}

  {% if git_page_authors %}
    <div class="md-source-date">
      <small>
          Authors: {{ git_page_authors | default('enable mkdocs-git-authors-plugin') }}
      </small>
    </div>
  {% endif %}
{% endblock %}
```

When viewing the plugin output, with or without the `.mailmap` file present, we get the following:
![image](https://github.com/timvink/mkdocs-git-authors-plugin/assets/25905330/84c0156d-0616-4b1d-92a6-10728ee16185)
Which makes it look like the plugin is ignoring the `.mailmap` file. Is there perhaps something we can improve around how we use the plugin?

Here is our `requirements.txt`:
```
mkdocs==1.4.3
mkdocs-autorefs==0.4.1
mkdocs-awesome-pages-plugin==2.9.1
mkdocs-git-authors-plugin==0.7.2
mkdocs-git-revision-date-plugin==0.3.2
mkdocs-glightbox==0.3.4
mkdocs-htmlproofer-plugin==0.13.1
mkdocs-img2figv2-plugin==0.0.2
mkdocs-material-extensions==1.1.1
mkdocs-material==9.1.15
mkdocs-mermaid2-plugin==0.6.0
mkdocs-section-index==0.3.5
pymdown-extensions==10.0.1
```
```

**Comment by timvink** [comment]
It might be because the syntax of your `.mailmap` is wrong, as there should be a whitespace after the name. Try replacing:

```
JP S<jp.s@redacted.co.za> <DXtL4PyW7ExnRyGAbEvA>
Matthew V<matthew.v@redacted.co.uk> <matthew.v@redacted.co.za>
Matthew V<matthew.v@redacted.co.uk> <matthew.v@redacted.com>
```

with:

```
JP S <jp.s@redacted.co.za> <DXtL4PyW7ExnRyGAbEvA>
Matthew V <matthew.v@redacted.co.uk> <matthew.v@redacted.co.za>
Matthew V <matthew.v@redacted.co.uk> <matthew.v@redacted.com>
```

(More details on the syntax at https://git-scm.com/docs/gitmailmap).

---

If that doesn't fix it.. Perhaps the problem is that this plugin uses `git blame --porcelain` (which gives a machine readable version). 

We parse the `author` and `author-email`, instead of `committer` and `committer-email`. Can you check those are correct by manually running a `git blame --porcelain` ? 

---

Another check: are you running `mkdocs serve` / `mkdocs build` in the same directory as where the `.mailmap` file lives (the root of the project)?

**Comment by JPStrydom** [comment]
Thanks for the feedback. The `.mailmap` file format is correct in our codebase, I just broke the spacing when copying it across. I've updated my original message.

Let me double check the rest and get back to you. Thanks again for the advice 👍

**Comment by JPStrydom** [comment]
I found the issue! We (by we I mean I) weren't copying our `.mailmap` file in our `Dockerfile`. Seems like adding that did the trick. Thanks for the quick responses, and thanks for the plugin!
