### ISSUE TITLE
Support for Github Entperprise

### ISSUE THREAD

**Issue by vrenjith** [timvink/mkdocs-git-authors-plugin#83]
Hi,

Does this plugin support GitHub Enterprise?

Renjith

**Comment by timvink** [comment]
Hi @vrenjith ,

This plugin uses `git` directly, from the local filesystem. So the answer is no, it's not supported, but it *will* work just fine :) 

If you're looking to extract information from github (like your github avatar and such), have a look at https://github.com/ojacques/mkdocs-git-committers-plugin-2
