### ISSUE TITLE
Make Github username available like {email} and {name}

### ISSUE THREAD

**Issue by anitagirme** [timvink/mkdocs-git-authors-plugin#84]
## Description
Make Github username available like {email} and {name} so that it can be used in `href` options for creating link to user's profile.

## Definition of Done
- [ ]  {username} is available along with {email} and {name} and can be used in `href` option using the f-string format.

**Comment by timvink** [comment]
This is impossible as that information is not recorded by git. 

You can however retrieve the GitHub username (and additional information) using the GitHub api. There's another plugin to do that: https://github.com/ojacques/mkdocs-git-committers-plugin-2

See also these docs for more background info 
https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=git
