### ISSUE TITLE
Documentation section about mkdocs-material

### ISSUE THREAD

**Issue by vladislav-sharapov** [timvink/mkdocs-git-authors-plugin#86]
The mkdocs-git-authors-plugin documentation has [information](https://timvink.github.io/mkdocs-git-authors-plugin/usage.html#mkdocs-material-theme) about integration with the mkdocs-material theme, but in the latest version of mkdocs-material adding an override is [unnecessary](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-authors). Can we mention this in the mkdocs-git-authors-plugin documentation?

**Comment by timvink** [comment]
Yes, you're right! Thanks for pointing that out.

Would you be willing to make the changes to `docs/usage.md` and make a PR?

**Comment by vladislav-sharapov** [comment]
Yes, I can try.
