### ISSUE TITLE
AttributeError: 'File' object has no attribute 'src_dir' on line 121: if file.src_dir is None: 

### ISSUE THREAD

**Issue by bobneuman** [timvink/mkdocs-git-authors-plugin#99]
We updated our plugin and received an AttributeError: 'File' object has no attribute 'src_dir' 

File: .... /lib/python3.9/site-packages/mkdocs_git_authors_plugin/plugin.py", line 121, in on_files
    if file.src_dir is None:
AttributeError: 'File' object has no attribute 'src_dir'

This code was added in the merge on 25 Oct 2024 [blame](https://github.com/timvink/mkdocs-git-authors-plugin/blame/master/mkdocs_git_authors_plugin/plugin.py)

It needs to check for the attribute before the value in the same way as "hasattr(file, "generated_by")"
```
 if hasattr(file, 'src_dir') and file.src_dir is None:
```

**Comment by timvink** [comment]
Thanks for creating the issue! 

I just released the fix in a new version on pypi. Details here: https://github.com/timvink/mkdocs-git-authors-plugin/releases/tag/v0.9.2

Let me know if this fixes it
